[package]
name = "tip-game"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
crossterm = "0.22.1"
fastrand = "1.5.0"
lazy_static = "1.4.0"
